# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 05:10
from __future__ import unicode_literals

import DUEditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('Description', DUEditor.models.UEditorField(blank=True, verbose_name='描述')),
                ('ImagePath', models.CharField(blank=True, max_length=100, verbose_name='图片目录')),
                ('Content', DUEditor.models.UEditorField(blank=True, default='test', verbose_name='内容')),
            ],
        ),
    ]
